version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'qrcode'
      QR_CODE_DEFAULT_URL: 'https://github.com/kjc47'
      QR_CODE_DEFAULT_FILE_NAME: 'kjc47-github.png'
    volumes:
      - .:/home/myuser
      